version: '3.7'

services:
  migration:
    user: ${_UID}:${_GID}
    image: keycloak2cognito:local
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
      - ${PWD}:/app
